const axios = require("axios");
const fs = require("fs");
const path = require("path");

function formatBugDescription(bugData) {
  const timezone = process.env.TIMEZONE || 'UTC';
  const now = new Date().toLocaleString('en-US', { 
    timeZone: timezone,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: true
  });
  
  return `
# 🐞 Bug Report

## 📌 Summary
${bugData.description || "Not provided"}

---

## 🌐 Environment
- Platform: ${bugData.platform || "Not specified"}
- Environment: ${bugData.environment || "Not specified"}

---

## ⚙️ Preconditions
${bugData.preconditions || "Not provided"}

---

## 📋 Steps to Reproduce
${
  Array.isArray(bugData.steps)
    ? bugData.steps
        .map((step, index) => `${index + 1}. ${step}`)
        .join("\n")
    : bugData.steps || "Not provided"
}

---

## ❌ Actual Result
${bugData.actual || "Not provided"}

---

## ✅ Expected Result
${bugData.expected || "Not provided"}

---

## ⚠️ Severity
${bugData.severity || "Not provided"}

---

## 📎 Evidence
Attachments included in this card.

---

🕒 Generated: ${now} (${timezone})
🤖 Generated by Bug Agent
`;
}

function formatCardTitle(bugData) {
  const platform = bugData.platform || "Unknown";
  const severity = bugData.severity || "Medium";

  return `[${platform}][${severity}] ${bugData.title}`;
}

async function uploadToTrello(bugData, mediaFiles = []) {
  const { TRELLO_API_KEY, TRELLO_TOKEN, TRELLO_LIST_ID } = process.env;

  try {
    console.log("📤 Creating Trello card...");

    const cardResponse = await axios.post(
      "https://api.trello.com/1/cards",
      null,
      {
        params: {
          key: TRELLO_API_KEY,
          token: TRELLO_TOKEN,
          idList: TRELLO_LIST_ID,
          name: formatCardTitle(bugData),
          desc: formatBugDescription(bugData),
          pos: "top",
        },
      },
    );

    const cardId = cardResponse.data.id;

    console.log(`✅ Card created: ${cardResponse.data.shortUrl}`);

    // 📎 Upload attachments with better error handling
    const uploadResults = {
      successful: 0,
      failed: 0,
      skipped: 0,
    };

    if (!mediaFiles || mediaFiles.length === 0) {
      console.log("ℹ️ No attachments to upload.");
    } else {
      console.log(`📎 Uploading ${mediaFiles.length} attachment(s)...`);

      for (const file of mediaFiles) {
        try {
          // 1. Validar que el archivo exista
          if (!file.localPath) {
            console.warn(
              `⚠️ Skipped "${file.fileName}": no localPath provided`,
            );
            uploadResults.skipped += 1;
            continue;
          }

          if (!fs.existsSync(file.localPath)) {
            console.warn(
              `⚠️ Skipped "${file.fileName}": file not found at ${file.localPath}`,
            );
            uploadResults.skipped += 1;
            continue;
          }

          // 2. Verificar tamaño del archivo (Trello tiene límite)
          const fileSize = fs.statSync(file.localPath).size;
          const maxSize = 10 * 1024 * 1024; // 10 MB
          if (fileSize > maxSize) {
            console.warn(
              `⚠️ Skipped "${file.fileName}": file too large (${(fileSize / 1024 / 1024).toFixed(2)}MB > 10MB)`,
            );
            uploadResults.skipped += 1;
            continue;
          }

          // 3. Intentar subir
          console.log(
            `  → Uploading ${file.fileName} (${(fileSize / 1024).toFixed(2)}KB)...`,
          );

          await axios.postForm(
            `https://api.trello.com/1/cards/${cardId}/attachments`,
            {
              key: TRELLO_API_KEY,
              token: TRELLO_TOKEN,
              file: fs.createReadStream(file.localPath),
              name: file.fileName,
            },
          );

          console.log(`  ✅ ${file.fileName} uploaded successfully`);
          uploadResults.successful += 1;
        } catch (err) {
          console.error(
            `  ❌ Failed to upload "${file.fileName}": ${err.message}`,
          );
          uploadResults.failed += 1;
        }
      }

      console.log(
        `\n📊 Upload summary: ${uploadResults.successful} successful, ${uploadResults.failed} failed, ${uploadResults.skipped} skipped`,
      );

      if (uploadResults.successful === 0 && mediaFiles.length > 0) {
        throw new Error(
          `Failed to upload any attachments. Check logs for details.`,
        );
      }
    }

    return cardResponse.data;
  } catch (error) {
    const errorDetail = error.response
      ? JSON.stringify(error.response.data)
      : error.message;

    throw new Error(`Trello Upload Failed: ${errorDetail}`);
  }
}

module.exports = { uploadToTrello };