

const axios = require("axios");
const fs = require("fs");

function formatBugDescription(bugData) {
  return `
# 🐞 Bug Report

## 📌 Summary
${bugData.description || "Not provided"}

---

## 🌐 Environment
- Platform: ${bugData.platform || "Not specified"}
- Environment: ${bugData.environment || "Not specified"}

---

## ⚙️ Preconditions
${bugData.preconditions || "Not provided"}

---

## 📋 Steps to Reproduce
${
  Array.isArray(bugData.steps)
    ? bugData.steps
        .map((step, index) => `${index + 1}. ${step}`)
        .join("\n")
    : bugData.steps || "Not provided"
}

---

## ❌ Actual Result
${bugData.actual || "Not provided"}

---

## ✅ Expected Result
${bugData.expected || "Not provided"}

---

## ⚠️ Severity
${bugData.severity || "Not provided"}

---

## 📎 Evidence
Attachments included in this card.

---

🕒 Generated: ${new Date().toLocaleString()}
🤖 Generated by Bug Agent
`;
}

function formatCardTitle(bugData) {
  const platform = bugData.platform || "Unknown";
  const severity = bugData.severity || "Medium";

  return `[${platform}][${severity}] ${bugData.title}`;
}

async function uploadToTrello(bugData, mediaFiles = []) {
  const { TRELLO_API_KEY, TRELLO_TOKEN, TRELLO_LIST_ID } = process.env;

  try {
    console.log("📤 Creating Trello card...");

    const cardResponse = await axios.post(
      "https://api.trello.com/1/cards",
      null,
      {
        params: {
          key: TRELLO_API_KEY,
          token: TRELLO_TOKEN,
          idList: TRELLO_LIST_ID,
          name: formatCardTitle(bugData),
          desc: formatBugDescription(bugData),
          pos: "top",
        },
      },
    );

    const cardId = cardResponse.data.id;

    console.log(`✅ Card created: ${cardResponse.data.shortUrl}`);

    // 📎 Upload attachments
    for (const file of mediaFiles) {
      console.log(`📎 Attaching ${file.fileName}...`);

      await axios.postForm(
        `https://api.trello.com/1/cards/${cardId}/attachments`,
        {
          key: TRELLO_API_KEY,
          token: TRELLO_TOKEN,
          file: fs.createReadStream(file.localPath),
          name: file.fileName,
        },
      );
    }

    console.log("✅ All attachments uploaded.");

    return cardResponse.data;

  } catch (error) {
    const errorDetail = error.response
      ? JSON.stringify(error.response.data)
      : error.message;

    throw new Error(`Trello Upload Failed: ${errorDetail}`);
  }
}

module.exports = { uploadToTrello };
